name: "OWASP Amass Enum"
description: "In-depth Attack Surface Mapping and Asset Discovery"
branding:
  icon: "eye"
  color: "gray-dark"

inputs:
  domains:
    description: "Domain names separated by commas (can be used multiple times)"
    required: true

  passive:
    description: "Disable DNS resolution of names and dependent features"
    required: false
    default: false

  timeout:
    description: "This will stop enumerating a domain after X amount of MINUTES, to guarantee the time spent enumeration."
    required: false

  dnsfile:
    description: "Path to a file providing untrusted DNS resolvers"
    required: false

  dnsqps:
    description: "Maximum number of DNS queries per second across all resolvers"
    required: false
    
  brute:
    description: "Execute brute forcing after searches"
    required: false
    default: false
  
  output:
    description: "Path to the text file containing terminal stdout/stderr"
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
